### ISSUE TITLE
Deux problemes :

### ISSUE THREAD

**Issue by Soifox** [TomLaVachette/svmod#24]
Bonjour :)

J'ai deux petits (enfin, facon de parler) problèmes :
    - Les véhicules ne dispawn pas quand ils sont détruits
    - Les joueurs prennent des dégâts quand ils foncent dans les murs alors que la variables est a 0

Probleme présent sur la version workshop comme sur la version github et le code n'a pas été modifié.

**Comment by djtb2924** [comment]
Tu n’as pas d’autres addons qui interfèrent avec les hooks du SVMOD ?

**Comment by Soifox** [comment]
Hey, 

Non c'est bon, depuis le temps j'ai tout fix :P

Mais merci quand même !
