### ISSUE TITLE
Please add a LICENSE and or Privacy Policy to the project

### ISSUE THREAD

**Issue by xray-tango** [TomLaVachette/svmod#29]
"Is this project Open source? Freeware? Propitiatory?"
"Do I have the Permission to do X and do Y with it?"
"What am I'm prohibited from doing with it?"
"What are the Conditions to use and modify it?"
"Can I self host it?"
"What is the privacy policy, what data does this collect and use?"
"Is the whole source code visible or are there hidden and inaccessible parts of it like a DRM API?"

These are some of the questions people have when they see a project without any license or privacy policy stated. 
People having access to these basic information in a form of a LICENSE and or a Privacy Policy can prevent inevitable misuse of the project and will add a lot to it's integrity and image!

On GitHub it's very easy to add a LICENSE to the project and can be done with in minutes. Please do so for everyone's benefit!

**Comment by thejaviertc** [comment]
Exactly, without LICENSE, technically we have no permission from the creators of the software to use, modify, or share the software. With a LICENSE, users would be able to know what things can do or not with SVMod (contribute to the project, modify it...).

As @xray-tango said, you can have it done in just a minute, just choosing what license you want to use and it's automatically generated.
You can see what licenses are available at https://choosealicense.com/. Maybe a MIT or GNU GPL will be enough.
